"""initial_schema

Revision ID: 42dacfc8fa0c
Revises: 
Create Date: 2026-01-22 22:10:48.389760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42dacfc8fa0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jibble_email_mapping', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('jibble_person', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('jibble_time_entry', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default='now()',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jibble_time_entry', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("'2026-01-22 20:58:06.634992'::timestamp without time zone"),
               existing_nullable=True)
    op.alter_column('jibble_person', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("'2026-01-22 20:58:06.634992'::timestamp without time zone"),
               existing_nullable=True)
    op.alter_column('jibble_email_mapping', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("'2026-01-22 20:58:06.634992'::timestamp without time zone"),
               existing_nullable=True)
    # ### end Alembic commands ###
