"""add_performance_indexes

Revision ID: f8c6dd008b21
Revises: 42dacfc8fa0c
Create Date: 2026-01-22 22:48:21.886894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8c6dd008b21'
down_revision: Union[str, None] = '42dacfc8fa0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_contributor_email', 'contributor', ['turing_email'], unique=False)
    op.create_index(op.f('ix_contributor_name'), 'contributor', ['name'], unique=False)
    op.create_index(op.f('ix_contributor_status'), 'contributor', ['status'], unique=False)
    op.create_index(op.f('ix_contributor_team_lead_id'), 'contributor', ['team_lead_id'], unique=False)
    op.create_index('ix_contributor_team_lead_type', 'contributor', ['team_lead_id', 'type'], unique=False)
    op.create_index(op.f('ix_contributor_type'), 'contributor', ['type'], unique=False)
    op.create_index('ix_contributor_daily_composite', 'contributor_daily_stats', ['contributor_id', 'submission_date'], unique=False)
    op.create_unique_constraint('uq_contributor_daily_stats', 'contributor_daily_stats', ['contributor_id', 'submission_date'])
    op.alter_column('jibble_email_mapping', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('jibble_person', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('jibble_time_entry', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default='now()',
               existing_nullable=True)
    op.create_index('ix_jibble_time_person_date', 'jibble_time_entry', ['person_id', 'entry_date'], unique=False)
    op.create_unique_constraint('uq_jibble_time_entry', 'jibble_time_entry', ['person_id', 'entry_date'])
    op.create_index(op.f('ix_review_detail_conversation_id'), 'review_detail', ['conversation_id'], unique=False)
    op.create_index('ix_review_detail_conversation_reviewer', 'review_detail', ['conversation_id', 'reviewer_id'], unique=False)
    op.create_index(op.f('ix_review_detail_domain'), 'review_detail', ['domain'], unique=False)
    op.create_index(op.f('ix_review_detail_human_role_id'), 'review_detail', ['human_role_id'], unique=False)
    op.create_index(op.f('ix_review_detail_is_delivered'), 'review_detail', ['is_delivered'], unique=False)
    op.create_index(op.f('ix_review_detail_review_id'), 'review_detail', ['review_id'], unique=False)
    op.create_index('ix_review_detail_reviewer_domain', 'review_detail', ['reviewer_id', 'domain'], unique=False)
    op.create_index(op.f('ix_review_detail_reviewer_id'), 'review_detail', ['reviewer_id'], unique=False)
    op.create_index('ix_review_detail_updated_at', 'review_detail', ['updated_at'], unique=False)
    op.create_index('ix_reviewer_daily_composite', 'reviewer_daily_stats', ['reviewer_id', 'review_date'], unique=False)
    op.create_unique_constraint('uq_reviewer_daily_stats', 'reviewer_daily_stats', ['reviewer_id', 'review_date'])
    op.create_index('ix_reviewer_trainer_daily_composite', 'reviewer_trainer_daily_stats', ['reviewer_id', 'trainer_id', 'review_date'], unique=False)
    op.create_index('ix_reviewer_trainer_date', 'reviewer_trainer_daily_stats', ['reviewer_id', 'review_date'], unique=False)
    op.create_unique_constraint('uq_reviewer_trainer_daily_stats', 'reviewer_trainer_daily_stats', ['reviewer_id', 'trainer_id', 'review_date'])
    op.create_index(op.f('ix_task_created_at'), 'task', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_current_user_id'), 'task', ['current_user_id'], unique=False)
    op.create_index('ix_task_current_user_status', 'task', ['current_user_id', 'status'], unique=False)
    op.create_index(op.f('ix_task_domain'), 'task', ['domain'], unique=False)
    op.create_index(op.f('ix_task_is_delivered'), 'task', ['is_delivered'], unique=False)
    op.create_index('ix_task_last_completed_date', 'task', ['last_completed_date'], unique=False)
    op.create_index('ix_task_project_batch', 'task', ['project_id', 'batch_id'], unique=False)
    op.create_index(op.f('ix_task_project_id'), 'task', ['project_id'], unique=False)
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    op.create_index('ix_task_status_domain', 'task', ['status', 'domain'], unique=False)
    op.create_index(op.f('ix_task_updated_at'), 'task', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_updated_at'), table_name='task')
    op.drop_index('ix_task_status_domain', table_name='task')
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_index(op.f('ix_task_project_id'), table_name='task')
    op.drop_index('ix_task_project_batch', table_name='task')
    op.drop_index('ix_task_last_completed_date', table_name='task')
    op.drop_index(op.f('ix_task_is_delivered'), table_name='task')
    op.drop_index(op.f('ix_task_domain'), table_name='task')
    op.drop_index('ix_task_current_user_status', table_name='task')
    op.drop_index(op.f('ix_task_current_user_id'), table_name='task')
    op.drop_index(op.f('ix_task_created_at'), table_name='task')
    op.drop_constraint('uq_reviewer_trainer_daily_stats', 'reviewer_trainer_daily_stats', type_='unique')
    op.drop_index('ix_reviewer_trainer_date', table_name='reviewer_trainer_daily_stats')
    op.drop_index('ix_reviewer_trainer_daily_composite', table_name='reviewer_trainer_daily_stats')
    op.drop_constraint('uq_reviewer_daily_stats', 'reviewer_daily_stats', type_='unique')
    op.drop_index('ix_reviewer_daily_composite', table_name='reviewer_daily_stats')
    op.drop_index('ix_review_detail_updated_at', table_name='review_detail')
    op.drop_index(op.f('ix_review_detail_reviewer_id'), table_name='review_detail')
    op.drop_index('ix_review_detail_reviewer_domain', table_name='review_detail')
    op.drop_index(op.f('ix_review_detail_review_id'), table_name='review_detail')
    op.drop_index(op.f('ix_review_detail_is_delivered'), table_name='review_detail')
    op.drop_index(op.f('ix_review_detail_human_role_id'), table_name='review_detail')
    op.drop_index(op.f('ix_review_detail_domain'), table_name='review_detail')
    op.drop_index('ix_review_detail_conversation_reviewer', table_name='review_detail')
    op.drop_index(op.f('ix_review_detail_conversation_id'), table_name='review_detail')
    op.drop_constraint('uq_jibble_time_entry', 'jibble_time_entry', type_='unique')
    op.drop_index('ix_jibble_time_person_date', table_name='jibble_time_entry')
    op.alter_column('jibble_time_entry', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("'2026-01-22 20:58:06.634992'::timestamp without time zone"),
               existing_nullable=True)
    op.alter_column('jibble_person', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("'2026-01-22 20:58:06.634992'::timestamp without time zone"),
               existing_nullable=True)
    op.alter_column('jibble_email_mapping', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("'2026-01-22 20:58:06.634992'::timestamp without time zone"),
               existing_nullable=True)
    op.drop_constraint('uq_contributor_daily_stats', 'contributor_daily_stats', type_='unique')
    op.drop_index('ix_contributor_daily_composite', table_name='contributor_daily_stats')
    op.drop_index(op.f('ix_contributor_type'), table_name='contributor')
    op.drop_index('ix_contributor_team_lead_type', table_name='contributor')
    op.drop_index(op.f('ix_contributor_team_lead_id'), table_name='contributor')
    op.drop_index(op.f('ix_contributor_status'), table_name='contributor')
    op.drop_index(op.f('ix_contributor_name'), table_name='contributor')
    op.drop_index('ix_contributor_email', table_name='contributor')
    # ### end Alembic commands ###
